// Code generated by goctl. DO NOT EDIT.
package types

type HelloReq struct {
	User string `form:"user"`
}

type HelloResp struct {
	Msg string `json:"msg"`
}

type CheckReq struct {
	Token string `form:"token"`
}

type CheckResp struct {
	Ok bool `json:"ok"`
}

type AddReq struct {
	User  string `form:"user"`
	Phone string `from:"phone"`
}

type AddResp struct {
	ErrMsg    string `json:"status"`
	ErrorCode int64  `json:"error_code"`
}
