// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bookstore.proto

package bookstore

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f82f486e563a88c, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f82f486e563a88c, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type CheckReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckReq) Reset()         { *m = CheckReq{} }
func (m *CheckReq) String() string { return proto.CompactTextString(m) }
func (*CheckReq) ProtoMessage()    {}
func (*CheckReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f82f486e563a88c, []int{2}
}

func (m *CheckReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckReq.Unmarshal(m, b)
}
func (m *CheckReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckReq.Marshal(b, m, deterministic)
}
func (m *CheckReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckReq.Merge(m, src)
}
func (m *CheckReq) XXX_Size() int {
	return xxx_messageInfo_CheckReq.Size(m)
}
func (m *CheckReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckReq proto.InternalMessageInfo

func (m *CheckReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CheckResp struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckResp) Reset()         { *m = CheckResp{} }
func (m *CheckResp) String() string { return proto.CompactTextString(m) }
func (*CheckResp) ProtoMessage()    {}
func (*CheckResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f82f486e563a88c, []int{3}
}

func (m *CheckResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResp.Unmarshal(m, b)
}
func (m *CheckResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResp.Marshal(b, m, deterministic)
}
func (m *CheckResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResp.Merge(m, src)
}
func (m *CheckResp) XXX_Size() int {
	return xxx_messageInfo_CheckResp.Size(m)
}
func (m *CheckResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResp proto.InternalMessageInfo

func (m *CheckResp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type AddReq struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReq) Reset()         { *m = AddReq{} }
func (m *AddReq) String() string { return proto.CompactTextString(m) }
func (*AddReq) ProtoMessage()    {}
func (*AddReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f82f486e563a88c, []int{4}
}

func (m *AddReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReq.Unmarshal(m, b)
}
func (m *AddReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReq.Marshal(b, m, deterministic)
}
func (m *AddReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReq.Merge(m, src)
}
func (m *AddReq) XXX_Size() int {
	return xxx_messageInfo_AddReq.Size(m)
}
func (m *AddReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddReq proto.InternalMessageInfo

func (m *AddReq) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *AddReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type AddResp struct {
	ErrMsg               string   `protobuf:"bytes,1,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	ErrCode              string   `protobuf:"bytes,2,opt,name=errCode,proto3" json:"errCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResp) Reset()         { *m = AddResp{} }
func (m *AddResp) String() string { return proto.CompactTextString(m) }
func (*AddResp) ProtoMessage()    {}
func (*AddResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f82f486e563a88c, []int{5}
}

func (m *AddResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResp.Unmarshal(m, b)
}
func (m *AddResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResp.Marshal(b, m, deterministic)
}
func (m *AddResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResp.Merge(m, src)
}
func (m *AddResp) XXX_Size() int {
	return xxx_messageInfo_AddResp.Size(m)
}
func (m *AddResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddResp proto.InternalMessageInfo

func (m *AddResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *AddResp) GetErrCode() string {
	if m != nil {
		return m.ErrCode
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "bookstore.Request")
	proto.RegisterType((*Response)(nil), "bookstore.Response")
	proto.RegisterType((*CheckReq)(nil), "bookstore.CheckReq")
	proto.RegisterType((*CheckResp)(nil), "bookstore.CheckResp")
	proto.RegisterType((*AddReq)(nil), "bookstore.AddReq")
	proto.RegisterType((*AddResp)(nil), "bookstore.AddResp")
}

func init() { proto.RegisterFile("bookstore.proto", fileDescriptor_6f82f486e563a88c) }

var fileDescriptor_6f82f486e563a88c = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0x54, 0x53, 0xf2, 0xda, 0x03, 0x8f, 0xa5, 0x42, 0x51, 0x00, 0xa9, 0xf2, 0x89, 0x03, 0xaa,
	0x50, 0x38, 0x72, 0x2a, 0xbd, 0x70, 0xe1, 0xe2, 0x4f, 0x28, 0x5e, 0x51, 0xc9, 0x25, 0xeb, 0x7a,
	0xd3, 0xef, 0xe1, 0x57, 0x51, 0x1c, 0xa7, 0x94, 0xc7, 0x6d, 0x67, 0xc6, 0xb3, 0xf6, 0x8c, 0xe1,
	0x6c, 0xcd, 0x6c, 0xa5, 0x63, 0x4f, 0x0b, 0xe7, 0xb9, 0x63, 0x2c, 0x0f, 0x84, 0xba, 0x85, 0x5c,
	0xd3, 0x6e, 0x4f, 0xd2, 0x21, 0xc2, 0xc9, 0x5e, 0xc8, 0x57, 0x93, 0xf9, 0xe4, 0xae, 0xd4, 0x61,
	0x56, 0x37, 0x50, 0x68, 0x12, 0xc7, 0xad, 0x10, 0x9e, 0xc3, 0xf4, 0x43, 0xde, 0xa3, 0xdc, 0x8f,
	0x6a, 0x0e, 0xc5, 0x6a, 0x43, 0x6f, 0x56, 0xd3, 0x0e, 0x67, 0x90, 0x76, 0x6c, 0xa9, 0x8d, 0xfa,
	0x00, 0xd4, 0x35, 0x94, 0xf1, 0x84, 0x38, 0x3c, 0x85, 0x84, 0x6d, 0xd0, 0x0b, 0x9d, 0xb0, 0x55,
	0x0d, 0x64, 0x4b, 0x63, 0x7a, 0xf3, 0x3f, 0x57, 0xf7, 0x0b, 0xdd, 0x86, 0x5b, 0xaa, 0x92, 0x61,
	0x61, 0x00, 0xea, 0x09, 0xf2, 0xe0, 0x11, 0x87, 0x57, 0x90, 0x91, 0xf7, 0xaf, 0x87, 0x27, 0x45,
	0x84, 0x15, 0xe4, 0xe4, 0xfd, 0x8a, 0xcd, 0x68, 0x1d, 0x61, 0xf3, 0x39, 0x81, 0xf2, 0x79, 0x8c,
	0x8e, 0x0f, 0x90, 0xbe, 0xd0, 0x76, 0xcb, 0x88, 0x8b, 0xef, 0x82, 0x62, 0x19, 0xf5, 0xe5, 0x0f,
	0x2e, 0x36, 0xd0, 0x40, 0x1a, 0xd2, 0xe0, 0xb1, 0x3a, 0x36, 0x50, 0xcf, 0xfe, 0x92, 0xe2, 0xf0,
	0x1e, 0xa6, 0x4b, 0x63, 0xf0, 0xe2, 0x48, 0x1c, 0x42, 0xd7, 0xf8, 0x9b, 0x12, 0xb7, 0xce, 0xc2,
	0x07, 0x3d, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x79, 0xda, 0xae, 0xb3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookstoreClient is the client API for Bookstore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookstoreClient interface {
	Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Check(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*CheckResp, error)
	Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error)
}

type bookstoreClient struct {
	cc *grpc.ClientConn
}

func NewBookstoreClient(cc *grpc.ClientConn) BookstoreClient {
	return &bookstoreClient{cc}
}

func (c *bookstoreClient) Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/bookstore.Bookstore/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookstoreClient) Check(ctx context.Context, in *CheckReq, opts ...grpc.CallOption) (*CheckResp, error) {
	out := new(CheckResp)
	err := c.cc.Invoke(ctx, "/bookstore.Bookstore/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookstoreClient) Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error) {
	out := new(AddResp)
	err := c.cc.Invoke(ctx, "/bookstore.Bookstore/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookstoreServer is the server API for Bookstore service.
type BookstoreServer interface {
	Hello(context.Context, *Request) (*Response, error)
	Check(context.Context, *CheckReq) (*CheckResp, error)
	Add(context.Context, *AddReq) (*AddResp, error)
}

// UnimplementedBookstoreServer can be embedded to have forward compatible implementations.
type UnimplementedBookstoreServer struct {
}

func (*UnimplementedBookstoreServer) Hello(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (*UnimplementedBookstoreServer) Check(ctx context.Context, req *CheckReq) (*CheckResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (*UnimplementedBookstoreServer) Add(ctx context.Context, req *AddReq) (*AddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterBookstoreServer(s *grpc.Server, srv BookstoreServer) {
	s.RegisterService(&_Bookstore_serviceDesc, srv)
}

func _Bookstore_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookstore.Bookstore/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServer).Hello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookstore_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookstore.Bookstore/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServer).Check(ctx, req.(*CheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bookstore_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookstoreServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bookstore.Bookstore/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookstoreServer).Add(ctx, req.(*AddReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bookstore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bookstore.Bookstore",
	HandlerType: (*BookstoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Bookstore_Hello_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _Bookstore_Check_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Bookstore_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bookstore.proto",
}
